name: Pull Request Workflow
permissions: read-all
env:
    GITHUB_AUTH: secrets.GITHUB_AUTH
    MODEL_REVIEW_CALLBACK: secrets.MODEL_REVIEW_CALLBACK
    PR_NUMBER: ${{ github.event.number }}

    # Long-lived JWT token to identify the caller.
    MODEL_REVIEW_JWT: secrets.JWT

on:
    workflow_call:
        # Inputs the workflow accepts.
        inputs:
            type:
                type: string
                required: true
            pr_number:
                type: string
                required: true
            repo:
                type: string
                required: true
            owner:
                type: string
                required: true

        secrets:
            GITHUB_AUTH:
                required: true
            MODEL_REVIEW_CALLBACK:
                required: true
            MODEL_REVIEW_JWT:
                required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    start:
        runs-on: ubuntu-latest

        steps:
            - name: Is review or summary?
              run: echo "You've chosen to have the model ${{ inputs.type }} your Pull Request"
            - if: ${{ inputs.type == 'review'}}
              run: |
                  echo "Pull Request Number: ${{ inputs.pr_number }}"
                  echo "Repository: ${{ inputs.repo }}"
                  echo "Owner: ${{ inputs.owner }}"
