
name: Pull Request Workflow
permissions: read-all
env:
    GITHUB_AUTH: secrets.GITHUB_AUTH
    MODEL_REVIEW_CALLBACK: secrets.MODEL_REVIEW_CALLBACK
    PR_NUMBER: ${{ github.event.number }}

    # Long-lived JWT token to identify the caller.
    MODEL_REVIEW_JWT: secrets.JWT

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    workflow_dispatch:
        # Inputs the workflow accepts.
        inputs:
            type:
                type: choice
                description: Review or Summary?
                options:
                    - review
                    - summarize

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    start:
        runs-on: ubuntu-latest

        steps:
            - name: Is review or summary?
              run: echo "You've chosen to have the model ${{ inputs.name }} your Pull Request"
            - if: ${{ inputs.type == 'review'}}
              run: |
                  echo "Pull Request Number: ${{ github.event.number }}"
                  echo "Repository: ${{ github.repository }}"
