name: AI Review Comment
permissions: read-all
on:
    issue_comment:
        types: [created, edited]
jobs:
    echo_details:
        runs-on: ubuntu-latest
        steps:
            - name: Echo details
              run: |
                  echo "Below are the inputs passed to the workflow:"
                  echo "${{ toJson(github.event) }}"
    pr_commented:
        needs: echo_details
        if: ${{ github.event.issue.pull_request && github.event.comment.body == 'Review' }}
        uses: ./.github/workflows/manual.yml
        with:
            type: "review"
            pr_number: ${{ github.event.issue.number }}
            repo: ${{ github.event.repository.full_name }}
            owner: ${{ github.event.repository.owner.login }}
        secrets:
            GITHUB_AUTH: ${{ secrets.GITHUB_AUTH }}
            MODEL_REVIEW_CALLBACK: ${{ secrets.MODEL_REVIEW_CALLBACK }}
            MODEL_REVIEW_JWT: ${{ secrets.JWT }}

    finalize:
        runs-on: ubuntu-latest
        needs: pr_commented
        if: (needs.pr_commented.result == 'skipped') || success()
        steps:
            - name: Finalize
              run: echo "Finalizing the workflow after the review comment."
